### ISSUE TITLE
show figures

### ISSUE THREAD

**Issue by soltani123-Bilel** [baranwa2/Struct2Graph#3]
hello how can i see the figures plesae 
thanks

**Comment by baranwa2** [comment]
The figures are SVG files. You can view them in Inkscape or simply open them in a browser.

**Comment by Soltani-Bilel** [comment]
How open them.in a browser

**Comment by baranwa2** [comment]
Just download the files - right click --> Open with --> Choose Chrome/Firefox/Edge

**Comment by Soltani-Bilel** [comment]
Can i see them before running the project it's possible
